# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "byebug"
gem "sinatra"
gem "activerecord"
gem "sqlite3"
gem "httparty"
# gem 'pistonqueue', path: '../' # for test in localhost
gem 'pistonqueue', git: 'git@github.com:solehudinmq/pistonqueue.git', branch: 'main'
gem "rackup", "~> 2.2"
gem "puma", "~> 7.0"
